# Generated by Django 4.0.4 on 2022-05-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-last_login', '-date_joined']},
        ),
    ]
