# Generated by Django 4.0.4 on 2022-05-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_variation_margin_price_remove_variation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='size',
        ),
    ]
