# Generated by Django 4.0.4 on 2022-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_variation_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('product', models.ManyToManyField(to='store.variation')),
            ],
        ),
    ]
