# Generated by Django 4.0.4 on 2022-05-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='VarientSize',
        ),
    ]
