# Generated by Django 4.0.4 on 2022-05-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_size_varientsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='stock',
        ),
    ]
