# Generated by Django 4.0.4 on 2022-06-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_stock_alter_product_margin_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.varientsize'),
        ),
    ]
