# Generated by Django 4.0.4 on 2022-06-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_variation_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varientsize',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='varientsize',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
