# Generated by Django 4.0.4 on 2022-05-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='uer',
            new_name='user',
        ),
    ]
