# Generated by Django 4.0.4 on 2022-06-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderproduct_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='test',
            new_name='text',
        ),
    ]
